import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import {
  BaseImportService,
  ImportRun,
  PreparedRow,
  RowValidation,
} from 'src/common/excel/base-import.service';
import { ExcelService } from 'src/common/excel/excel.service';
import { ImportTemplateDefinition } from 'src/common/excel/import-template.interface';
import {
  RowErrorCollector,
  decimalAmount,
  enumValue,
  isoDate,
  optionalText,
  requiredText,
} from 'src/common/excel/import-validators';
import { AuditAction, AuditModule } from 'src/common/enums/audit-action.enum';
import { ProjectStatus } from 'src/common/enums/project-status.enum';
import {
  AuthenticatedUser,
  RequestContext,
} from 'src/common/interfaces/authenticated-user.interface';
import { AuditLogService } from 'src/modules/audit-logs/audit-log.service';
import { ImportReferenceService } from 'src/modules/imports/services/import-reference.service';
import { CreateProjectDto } from '../dto/project.dto';
import { Project } from '../entities/project.entity';
import { ProjectsService } from '../projects.service';

const PROJECT_TEMPLATE: ImportTemplateDefinition = {
  module: 'projects',
  label: 'Projects',
  sheetName: 'Projects',
  fileName: 'devstree-projects-import-template',
  notes: [
    'Project ID (PRJ-0001) is generated by the system — do not include it.',
    'Project Amount is OPTIONAL. Leave it blank for monthly, retainer or open-ended work.',
    'A blank Project Amount means the project has no predefined value. It does NOT mean zero: such projects still accept payments, and no due amount is calculated for them.',
    'The client must already exist. Import clients first if necessary.',
    'A project name that already exists for the same client is reported as a duplicate and is not imported.',
  ],
  columns: [
    {
      key: 'client',
      header: 'Client',
      required: true,
      type: 'string',
      example: 'John Doe',
      secondExample: 'CLI-0002',
      description: 'Client name, email or client code. Must already exist.',
      width: 26,
    },
    {
      key: 'projectName',
      header: 'Project Name',
      required: true,
      type: 'string',
      example: 'Website Development',
      secondExample: 'SEO Retainer',
      maxLength: 180,
      description: 'Must be unique for the client.',
      width: 30,
    },
    {
      key: 'description',
      header: 'Description',
      required: false,
      type: 'string',
      example: 'Corporate website with CMS',
      secondExample: 'Monthly SEO and content retainer',
      maxLength: 2000,
      width: 34,
    },
    {
      key: 'projectAmount',
      header: 'Project Amount',
      required: false,
      type: 'decimal',
      example: '50000',
      secondExample: '',
      format: 'Positive number, e.g. 50000 or 50000.00',
      description:
        'OPTIONAL. Leave blank when the project has no fixed value — blank is not zero. The second example row shows a retainer project with no amount.',
      width: 18,
    },
    {
      key: 'startDate',
      header: 'Start Date',
      required: false,
      type: 'date',
      example: '2026-01-15',
      secondExample: '',
      format: 'YYYY-MM-DD',
      width: 16,
    },
    {
      key: 'status',
      header: 'Status',
      required: false,
      type: 'enum',
      example: 'ACTIVE',
      secondExample: 'DRAFT',
      allowedValues: Object.values(ProjectStatus),
      description:
        'Defaults to DRAFT when blank. DRAFT and CANCELLED projects cannot receive payments.',
      width: 14,
    },
  ],
};

/**
 * Bulk project import.
 *
 * The one rule worth stating twice: a blank Project Amount column produces a
 * project with all four ciphertext columns NULL — the stored encoding of "no
 * predefined amount" — and never an encrypted zero. Everything downstream
 * (due calculation, payment ceiling, the VARIABLE payment status) depends on
 * that distinction, so the column is validated as optional and coerced with
 * `undefined`, never `0`.
 */
@Injectable()
export class ProjectsImportService extends BaseImportService<CreateProjectDto> {
  constructor(
    excel: ExcelService,
    auditLog: AuditLogService,
    @InjectRepository(Project) private readonly projects: Repository<Project>,
    private readonly references: ImportReferenceService,
    private readonly projectsService: ProjectsService,
    private readonly dataSource: DataSource,
  ) {
    super(excel, auditLog);
  }

  protected get definition(): ImportTemplateDefinition {
    return PROJECT_TEMPLATE;
  }

  protected get auditModule(): AuditModule {
    return AuditModule.PROJECTS;
  }

  protected async prepareRow(
    values: Record<string, string>,
    run: ImportRun<CreateProjectDto>,
  ): Promise<RowValidation<CreateProjectDto>> {
    const errors = new RowErrorCollector();

    const projectName = requiredText(values.projectName ?? '', 'Project Name', errors, 180);
    const description = optionalText(values.description ?? '', 'Description', errors, 2000);
    const startDate = isoDate(values.startDate ?? '', 'Start Date', errors, { required: false });
    const status = enumValue(values.status ?? '', 'Status', errors, Object.values(ProjectStatus), {
      required: false,
      fallback: ProjectStatus.DRAFT,
    });

    // `undefined` here means the cell was blank — a project with no fixed
    // amount. It must never be turned into 0.
    const projectAmount = decimalAmount(values.projectAmount ?? '', 'Project Amount', errors, {
      required: false,
    });

    const client = await this.references.resolveClient(values.client ?? '');
    if (!client.ok) errors.add('Client', client.error);

    if (errors.hasErrors || !client.ok) return { errors: errors.list };

    const clientRecord = client.value;
    const name = projectName as string;

    if (!run.claim('clientProject', `${clientRecord.id}|${name.toLowerCase()}`)) {
      return {
        duplicate: true,
        errors: [
          {
            row: 0,
            field: 'Project Name',
            error: `"${name}" appears more than once for client ${clientRecord.name} in this file.`,
          },
        ],
      };
    }

    const existing = await this.projects
      .createQueryBuilder('project')
      .where('project.deleted_at IS NULL')
      .andWhere('project.client_id = :clientId', { clientId: clientRecord.id })
      .andWhere('LOWER(project.project_name) = :name', { name: name.toLowerCase() })
      .getOne();

    if (existing) {
      return {
        duplicate: true,
        errors: [
          {
            row: 0,
            field: 'Project Name',
            error: `Client ${clientRecord.name} already has a project named "${name}" (${existing.projectCode}).`,
          },
        ],
      };
    }

    return {
      errors: [],
      prepared: {
        clientId: clientRecord.id,
        projectName: name,
        description: description ?? undefined,
        // undefined = no fixed amount; the service stores NULL ciphertext.
        projectAmount: projectAmount ?? undefined,
        startDate: startDate ?? undefined,
        status: status ?? ProjectStatus.DRAFT,
      },
    };
  }

  protected async persist(
    rows: PreparedRow<CreateProjectDto>[],
    actor: AuthenticatedUser,
    context: RequestContext,
  ): Promise<number> {
    return this.dataSource.transaction(async (manager) => {
      for (const row of rows) {
        const project = await this.projectsService.createWithin(manager, row.data, actor);

        await this.auditLog.record(
          {
            action: AuditAction.PROJECT_CREATED,
            module: AuditModule.PROJECTS,
            recordId: project.id,
            description: `Imported project ${project.projectName} from Excel (row ${row.row})`,
            newValue: {
              projectName: project.projectName,
              clientId: project.clientId,
              status: project.status,
              // Whether an amount exists is not itself financial data; the
              // value is redacted by the audit writer regardless.
              hasProjectAmount: project.hasProjectAmount(),
              source: 'EXCEL_IMPORT',
            },
            actor,
            context,
          },
          manager,
        );
      }
      return rows.length;
    });
  }
}
