/** Stable, client-facing error identifiers. Never change an existing value. */
export enum ErrorCode {
  // Generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Financial security
  FINANCIAL_LOCKED = 'FINANCIAL_LOCKED',
  INVALID_ACCOUNT_PASSWORD = 'INVALID_ACCOUNT_PASSWORD',
  FINANCIAL_UNLOCK_THROTTLED = 'FINANCIAL_UNLOCK_THROTTLED',
  ACCOUNT_PASSWORD_NOT_SET = 'ACCOUNT_PASSWORD_NOT_SET',
  ENCRYPTION_KEY_UNAVAILABLE = 'ENCRYPTION_KEY_UNAVAILABLE',
  DECRYPTION_FAILED = 'DECRYPTION_FAILED',

  // Business
  CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',
  CLIENT_HAS_PROJECTS = 'CLIENT_HAS_PROJECTS',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_HAS_PAYMENTS = 'PROJECT_HAS_PAYMENTS',
  PROJECT_NOT_ACCEPTING_PAYMENTS = 'PROJECT_NOT_ACCEPTING_PAYMENTS',
  PROJECT_CLIENT_MISMATCH = 'PROJECT_CLIENT_MISMATCH',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_EXCEEDS_DUE = 'PAYMENT_EXCEEDS_DUE',
  PAYMENT_ALREADY_VOIDED = 'PAYMENT_ALREADY_VOIDED',
  PAYMENT_AMOUNT_INVALID = 'PAYMENT_AMOUNT_INVALID',
  RECEIPT_NOT_FOUND = 'RECEIPT_NOT_FOUND',
  DUPLICATE_CODE = 'DUPLICATE_CODE',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',

  // Passwords
  CURRENT_PASSWORD_INCORRECT = 'CURRENT_PASSWORD_INCORRECT',
  PASSWORD_REUSED = 'PASSWORD_REUSED',
  PASSWORDS_MUST_DIFFER = 'PASSWORDS_MUST_DIFFER',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
}
