import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, IsNull, Repository } from 'typeorm';
import {
  BaseImportService,
  ImportRun,
  PreparedRow,
  RowValidation,
} from 'src/common/excel/base-import.service';
import { ExcelService, ParsedRow } from 'src/common/excel/excel.service';
import { ImportTemplateDefinition } from 'src/common/excel/import-template.interface';
import {
  RowErrorCollector,
  enumValue,
  optionalEmail,
  optionalPhone,
  requiredText,
} from 'src/common/excel/import-validators';
import { AuditAction, AuditModule } from 'src/common/enums/audit-action.enum';
import { ClientStatus } from 'src/common/enums/client-status.enum';
import {
  AuthenticatedUser,
  RequestContext,
} from 'src/common/interfaces/authenticated-user.interface';
import { AuditLogService } from 'src/modules/audit-logs/audit-log.service';
import { ClientsService } from '../clients.service';
import { CreateClientDto } from '../dto/client.dto';
import { Client } from '../entities/client.entity';

const CLIENT_TEMPLATE: ImportTemplateDefinition = {
  module: 'clients',
  label: 'Clients',
  sheetName: 'Clients',
  fileName: 'devstree-clients-import-template',
  notes: [
    'Client ID (CLI-0001) is generated by the system — do not include it.',
    'Only Client Name, Email, Phone, Country and Status are imported. Any other column in the sheet is ignored.',
    'Email must be unique across all clients. Rows with an email that already exists are reported as duplicates and are not imported.',
    'Country must match one of the countries configured under Masters → Countries (name or code).',
    'Leave optional cells blank rather than typing "N/A" or "-".',
  ],
  columns: [
    {
      key: 'name',
      header: 'Client Name',
      required: true,
      type: 'string',
      example: 'John Doe',
      secondExample: 'Acme Retail',
      maxLength: 160,
      description: 'Required. Leading and trailing spaces are removed; a blank name is rejected.',
      width: 28,
    },
    {
      key: 'email',
      header: 'Email',
      required: false,
      type: 'string',
      example: 'john@example.com',
      secondExample: 'accounts@acme.example',
      description: 'Must be unique across clients. Used to detect duplicate rows.',
      format: 'name@example.com',
      width: 28,
    },
    {
      key: 'phone',
      header: 'Phone',
      required: false,
      type: 'string',
      example: '9876543210',
      secondExample: '+91 98250 11223',
      description: 'Digits, spaces, +, - and brackets only.',
      width: 20,
    },
    {
      key: 'country',
      header: 'Country',
      required: false,
      type: 'string',
      example: 'India',
      secondExample: 'United States',
      description: 'Must match an active country master by name or code (e.g. India or IN).',
      width: 20,
    },
    {
      key: 'status',
      header: 'Status',
      required: false,
      type: 'enum',
      example: 'ACTIVE',
      secondExample: 'INACTIVE',
      allowedValues: Object.values(ClientStatus),
      description: 'Defaults to ACTIVE when blank.',
      width: 14,
    },
  ],
};

/**
 * Bulk client import.
 *
 * Duplicate detection mirrors the rule the single-record endpoint already
 * enforces (one client per email address) and adds a name+phone match, which
 * is what a re-uploaded sheet actually looks like when the email column was
 * left empty. Rows that match are reported, never merged or silently skipped.
 */
@Injectable()
export class ClientsImportService extends BaseImportService<CreateClientDto> {
  /** Active country masters, loaded once per file. */
  private countries = new Map<string, string>();

  constructor(
    excel: ExcelService,
    auditLog: AuditLogService,
    @InjectRepository(Client) private readonly clients: Repository<Client>,
    private readonly clientsService: ClientsService,
    private readonly dataSource: DataSource,
  ) {
    super(excel, auditLog);
  }

  protected get definition(): ImportTemplateDefinition {
    return CLIENT_TEMPLATE;
  }

  protected get auditModule(): AuditModule {
    return AuditModule.CLIENTS;
  }

  protected async beforeRows(_rows: ParsedRow[]): Promise<void> {
    // The same lookup a form save uses: name and code both resolve to the
    // stored country name, so "IN", "in" and "India" persist identically.
    this.countries = await this.clientsService.countryLookup();
  }

  protected async prepareRow(
    values: Record<string, string>,
    run: ImportRun<CreateClientDto>,
  ): Promise<RowValidation<CreateClientDto>> {
    const errors = new RowErrorCollector();

    const name = requiredText(values.name ?? '', 'Client Name', errors, 160);
    const email = optionalEmail(values.email ?? '', 'Email', errors);
    const phone = optionalPhone(values.phone ?? '', 'Phone', errors);
    const status = enumValue(values.status ?? '', 'Status', errors, Object.values(ClientStatus), {
      required: false,
      fallback: ClientStatus.ACTIVE,
    });
    const country = this.resolveCountry(values.country ?? '', errors);

    if (errors.hasErrors || !name) return { errors: errors.list };

    const duplicate = await this.findDuplicate(email, name, phone, run);
    if (duplicate) {
      return {
        errors: [{ row: 0, field: duplicate.field, error: duplicate.error }],
        duplicate: true,
      };
    }

    return {
      errors: [],
      prepared: {
        name,
        email: email ?? undefined,
        phone: phone ?? undefined,
        country: country ?? undefined,
        status: status ?? ClientStatus.ACTIVE,
      },
    };
  }

  protected async persist(
    rows: PreparedRow<CreateClientDto>[],
    actor: AuthenticatedUser,
    context: RequestContext,
  ): Promise<number> {
    return this.dataSource.transaction(async (manager) => {
      for (const row of rows) {
        const client = await this.clientsService.createWithin(manager, row.data, actor);

        await this.auditLog.record(
          {
            action: AuditAction.CLIENT_CREATED,
            module: AuditModule.CLIENTS,
            recordId: client.id,
            description: `Imported client ${client.name} from Excel (row ${row.row})`,
            newValue: { name: client.name, email: client.email, source: 'EXCEL_IMPORT' },
            actor,
            context,
          },
          manager,
        );
      }
      return rows.length;
    });
  }

  private resolveCountry(raw: string, errors: RowErrorCollector): string | null {
    const text = raw.trim();
    if (text === '') return null;

    // With no country masters configured there is nothing to validate against,
    // so the typed value is stored as-is rather than rejecting every row.
    if (this.countries.size === 0) return text.slice(0, 80);

    const match = this.countries.get(text.toLowerCase());
    if (!match) {
      errors.add(
        'Country',
        `"${text}" is not a configured country. Use a country name or code from Masters → Countries.`,
      );
      return null;
    }
    return match;
  }

  private async findDuplicate(
    email: string | null,
    name: string,
    phone: string | null,
    run: ImportRun<CreateClientDto>,
  ): Promise<{ field: string; error: string } | null> {
    if (email) {
      if (!run.claim('email', email)) {
        return { field: 'Email', error: `Email "${email}" appears more than once in this file.` };
      }
      const existing = await this.clients.findOne({ where: { email, deletedAt: IsNull() } });
      if (existing) {
        return {
          field: 'Email',
          error: `A client with this email already exists (${existing.clientCode}).`,
        };
      }
    }

    if (phone) {
      const key = `${name.toLowerCase()}|${phone}`;
      if (!run.claim('namePhone', key)) {
        return {
          field: 'Client Name',
          error: `"${name}" with this phone number appears more than once in this file.`,
        };
      }

      const existing = await this.clients
        .createQueryBuilder('client')
        .where('client.deleted_at IS NULL')
        .andWhere('LOWER(client.name) = :name', { name: name.toLowerCase() })
        .andWhere('client.phone = :phone', { phone })
        .getOne();

      if (existing) {
        return {
          field: 'Client Name',
          error: `A client named "${name}" with this phone number already exists (${existing.clientCode}).`,
        };
      }
    }

    return null;
  }
}
